<a href="https://colab.research.google.com/github/EzhilAbel/I-MSc-C-25-26-ML/blob/main/SVM_CSV_demo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

# Create dataset
data = {
    "studied_hours": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "attendance": [50, 55, 60, 65, 70, 75, 80, 85, 90, 95],
    "marks": [35, 40, 45, 50, 55, 65, 70, 75, 80, 90]
}

df = pd.DataFrame(data)

# Create PASS/FAIL column
df["result"] = df["marks"].apply(lambda x: 1 if x >= 50 else 0)

# Save to CSV
df.to_csv("students.csv", index=False)

print("CSV file created successfully")
df

CSV file created successfully

   studied_hours  attendance  marks  result
0              1          50     35       0
1              2          55     40       0
2              3          60     45       0
3              4          65     50       1
4              5          70     55       1
5              6          75     65       1
6              7          80     70       1
7              8          85     75       1
8              9          90     80       1
9             10          95     90       1

In [ ]:
# Load CSV file
dataset = pd.read_csv("students.csv")

print("Dataset loaded:")
dataset

Dataset loaded:

   studied_hours  attendance  marks  result
0              1          50     35       0
1              2          55     40       0
2              3          60     45       0
3              4          65     50       1
4              5          70     55       1
5              6          75     65       1
6              7          80     70       1
7              8          85     75       1
8              9          90     80       1
9             10          95     90       1

In [ ]:
# Input features
X = dataset[["studied_hours", "attendance"]]

# Target output
y = dataset["result"]

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

print("Training samples:", X_train.shape)
print("Testing samples:", X_test.shape)

Training samples: (7, 2)
Testing samples: (3, 2)

In [ ]:
from sklearn.svm import SVC

# Create Linear SVM
linear_svm = SVC(kernel="linear")

# Train model
linear_svm.fit(X_train, y_train)

print("Linear SVM trained")

Linear SVM trained

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix

# Predict
y_pred = linear_svm.predict(X_test)

# Accuracy
accuracy = accuracy_score(y_test, y_pred)

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)

print("Predicted values:", y_pred)
print("Accuracy:", accuracy)
print("Confusion Matrix:\n", cm)

Predicted values: [1 0 1]
Accuracy: 1.0
Confusion Matrix:
 [[1 0]
 [0 2]]

In [ ]:
# Kernel SVM with RBF
kernel_svm = SVC(kernel="rbf", C=1, gamma="scale")

# Train model
kernel_svm.fit(X_train, y_train)

# Predict
y_pred_kernel = kernel_svm.predict(X_test)

# Accuracy
accuracy_kernel = accuracy_score(y_test, y_pred_kernel)

print("Kernel SVM Accuracy:", accuracy_kernel)

Kernel SVM Accuracy: 0.6666666666666666